# Generated by Django 5.2.16 on 2026-07-23 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^(\\d{7,9})?$', 'El teléfono debe tener entre 7 y 9 dígitos.')]),
        ),
    ]
