# Generated by Django 5.2.16 on 2026-07-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('TARJETA', 'Tarjeta'), ('YAPE', 'Yape'), ('PLIN', 'Plin')], max_length=20),
        ),
    ]
