"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import sys
from pathlib import Path
from decouple import config
from datetime import timedelta
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default = False, cast = bool)

# En .env: lista separada por comas. Debe incluir la IP de red local de la
# maquina que corre el servidor (ej. 192.168.1.X) para poder probar desde un
# celular fisico conectado a la misma WiFi, ademas de localhost/127.0.0.1.
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1',
    cast=lambda v: [host.strip() for host in v.split(',') if host.strip()]
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Terceros
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    # Local
    'core',
    'users',
    'products',
    'orders',
]

# Auth
AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}

# Los tests usan SQLite en memoria en vez de Postgres: más rápido y evita
# depender de que el usuario de la BD tenga permiso CREATEDB solo para correr
# `manage.py test`. No afecta al servidor real (runserver sigue usando Postgres).
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-pe'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Media en Supabase Storage (S3-compatible): en Render el disco es efimero,
# asi que las imagenes de producto subidas por admin se perderian en cada
# deploy si se guardaran localmente. Si hay credenciales configuradas se usa
# Supabase Storage; si no (dev local sin configurar esto), cae al filesystem
# de siempre para no romper el flujo de desarrollo.
AWS_STORAGE_BUCKET_NAME = config('SUPABASE_STORAGE_BUCKET', default='')

STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

if AWS_STORAGE_BUCKET_NAME:
    AWS_ACCESS_KEY_ID = config('SUPABASE_STORAGE_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = config('SUPABASE_STORAGE_SECRET_ACCESS_KEY')
    AWS_S3_ENDPOINT_URL = config('SUPABASE_STORAGE_ENDPOINT_URL')
    AWS_S3_REGION_NAME = config('SUPABASE_STORAGE_REGION', default='us-east-1')
    AWS_S3_ADDRESSING_STYLE = 'path'
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False
    STORAGES['default'] = {'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage'}

    # El endpoint S3 (arriba) exige requests firmados incluso para GET, asi
    # que sirve solo para subir/borrar. Para las URLs publicas que ve el
    # navegador hay que usar el endpoint "object/public" de Supabase en vez
    # del protocolo S3. El project ref se saca del propio endpoint de
    # Storage (no de DB_HOST: ese puede ser el connection pooler, con un
    # hostname totalmente distinto al del proyecto).
    _supabase_project_ref = urlparse(AWS_S3_ENDPOINT_URL).hostname.split('.')[0]
    AWS_S3_CUSTOM_DOMAIN = (
        f'{_supabase_project_ref}.supabase.co/storage/v1/object/public/{AWS_STORAGE_BUCKET_NAME}'
    )
else:
    STORAGES['default'] = {'BACKEND': 'django.core.files.storage.FileSystemStorage'}

# Firebase Admin SDK (notificaciones push). Archivo de credenciales, nunca
# subir a git (ver .gitignore). En Render no hay archivo: se puede pasar el
# JSON completo por variable de entorno (ver core/apps.py).
FIREBASE_CREDENTIALS_PATH = str(BASE_DIR / config('FIREBASE_CREDENTIALS_PATH', default='secrets/firebase-adminsdk.json'))
FIREBASE_CREDENTIALS_JSON = config('FIREBASE_CREDENTIALS_JSON', default='')

# Rest Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    # 'login'/'register' solo se aplican en las vistas que declaran
    # throttle_scope (ver users/views.py) - protege contra fuerza bruta.
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        'login': '10/min',
        'register': '5/min',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}

# Origenes permitidos para peticiones desde el navegador (CORS). No afecta a
# la app Android (OkHttp no aplica CORS, eso solo lo hacen los navegadores).
# Configurable desde .env para producción, mismo patrón que ALLOWED_HOSTS.
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173,http://127.0.0.1:5173',
    cast=lambda v: [origin.strip() for origin in v.split(',') if origin.strip()]
)

# Render (y la mayoria de PaaS) terminan TLS en un proxy y reenvian por HTTP
# interno: sin esto Django cree que la conexion nunca es HTTPS y rechaza los
# POST de /admin/ (CSRF) o genera links http:// en vez de https://.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Dominios desde los que se acepta un POST con cookie de sesion (solo aplica
# a /admin/; la API JWT usada por React/Android no pasa por aqui).
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='',
    cast=lambda v: [origin.strip() for origin in v.split(',') if origin.strip()]
)
